name: 'Refactoring'
description: Please describe the tasks for the refactoring.
title: '[Refactor] '
body:
  - type: markdown
    attributes:
      value: |
        Example: "[Refactor] Refactor Login"
  - type: textarea
    id: refactor-description
    attributes:
      label: ♻️ Issue
      description: Please describe what you are refactoring.
      placeholder: Please write a description.
    validations:
      required: true
  - type: input
    id: input_parent
    attributes:
      label: 🔢 Issue Number
      description: Please provide the previous issue number related to the refactoring.
      placeholder: '#IssueNumber'
    validations:
      required: true
  - type: textarea
    id: textarea_description
    attributes:
      label: 📣 Refactoring Purpose
      description: Please describe the purpose of the refactoring.
      placeholder: |
        1. Reason
        2. Reason
      render: ''
    validations:
      required: false
  - type: textarea
    id: refactor-list
    attributes:
      label: 📝 To-do
      description: Please list the tasks required for the refactoring.
      placeholder: Please write the list.
    validations:
      required: true
